### ISSUE TITLE
complete example

### ISSUE THREAD

**Issue by emidiao** [ezet/stripe_sdk#1]
hello, do you have a complete working example with SCA?
thanks

**Comment by ezet** [comment]
Hey! I am working on improving the examples. Also seems I forgot to include the examples here, but the most up-to-date examples currently are available here:

https://pub.dev/packages/stripe_sdk#-example-tab-

I am more than willing to assist you in setting it up though, and will add more documentation and examples as users ask questions :)

**Comment by duzenko** [comment]
What is EphemeralKey and where do I get it from exactly? Is there a Stripe doc related to it?

**Comment by ezet** [comment]
@duzenko https://stripe.com/docs/mobile/android/standard#creating-ephemeral-keys

But I'm updating the library as we speak, with some breaking changes. This removes the need for ephemeral keys when using SCA related features. Just finishing the documentation, then v2.0.0 will be published.

**Comment by ezet** [comment]
A new version is published, with updated documentation and working samples.

**Comment by duzenko** [comment]
You probably want to add a link to pub.dev as well in this github repo for user convenience?
