### ISSUE TITLE
Intended workflow with user-provided PaymentMethod & 3DS?

### ISSUE THREAD

**Issue by duzenko** [ezet/stripe_sdk#3]
I'm having a problem migrating the existing working code to 2.0

1. It's not clear how to provide a PaymentMethod into confirmSetupIntent. Here's how I do it
```
            final paymentMethod = await StripeApi.instance.createPaymentMethod(card.toPaymentMethod());
            print(paymentMethod);

            final intent = await StripeApi.instance.confirmSetupIntent(clientSecret, data: {
              'payment_method': paymentMethod['id'],
              'return_url': Stripe.getReturnUrl(),
            });
            print(intent);
```
Please confirm if it's the intended workflow or advise of a better way.

2. If the setup intent returns with status 'requires_action' then how do I handle next_action? The package does not export the `handleSetupIntent` function that seems to be used for this.
So I have to  copy-paste the handleSetupIntent to work around that.

<s>3. The biggest problem for now is handleSetupIntent returns the same intent data that I feed to it, even if the 3DS process completes. The intent status is still requires_action, etc. Please advise.</s>

I appreciate your work here very much. It's the only stripe flutter package I could find that does the job for my use case. And your effort is to maintain it is appreciated as well tremendously.

**Comment by duzenko** [comment]
3. I made a mistake of not actually checking what handleSetupIntent returns.

But questions 1 and 2 remain.

Here's my code so far

```
            final paymentMethod = await StripeApi.instance.createPaymentMethod(card.toPaymentMethod());
            print(paymentMethod);

            final intent = await StripeApi.instance.confirmSetupIntent(clientSecret, data: {
              'payment_method': paymentMethod['id'],
              'return_url': Stripe.getReturnUrl(),
            });
            print(intent);
            switch (intent['status']) {
              case 'succeeded':
                break;
              case 'requires_action':
                final intent = await handleSetupIntent(intent['next_action']);
                print(intent);
                break;
              default:
                return; // failure
            }
           // proceed with intent confirmed
```

**Comment by ezet** [comment]
I will add a method on `Stripe` to handle your use-case, with a payment method, in the next update. For now, you need to use your suggested method to handle this, or alternatively, you can create the `SetupIntent` on your server with the `PaymentMethod` already set. Then you an use `Stripe.confirmSetupIntent()`.

I will also export handleSetupIntent and handlePaymentIntent. For now you need to copy/paste that code.

Please let me know if there are any other issues.

**Comment by duzenko** [comment]
I assume you don't need to actually export the handleSetupIntent if you add a way to pass a paymentMethod to Stripe.confirmSetupIntent. It will likely be able to handle the payment action internally?

**Comment by ezet** [comment]
Yep, but there might be other use-cases I'm not handling yet, so might as well expose it as it may be useful for others. :)

**Comment by ezet** [comment]
Please report any issues so I can fix it. I'm not using every part of it in production, so I rely on feedback:smile:

**Comment by duzenko** [comment]
Is there a new version on pub.dev? Can't see it

**Comment by ezet** [comment]
No, not yet. Will have more time at the end of the week, and next week.

**Comment by ezet** [comment]
Updated on pub.dev
