### ISSUE TITLE
Add stripeAccount to higherlevel api

### ISSUE THREAD

**Issue by krolaw** [ezet/stripe_sdk#4]
Hi, love the idea with this plugin. Alas, I am struggling. I create my payment_intent on the server. In my app:
  final api = StripeApi(publishableKey);
  api.stripeAccount = accountID;
Now I want to bring up the card entry widget so I can authorise the card against the payment intent. I have the client secret, but I'm not sure what method to call.
The Stripe api looks simpler (I think), but I can't add the stripeAccount parameter. I'm wondering, if it was make an optional parameter in the Stripe constructor, everything would be easier.

Thanks again.

**Comment by ezet** [comment]
Currently, you need to create a payment method or card first, and then
provide its ID as an argument to the library methods, or set it on the
intent using your server. It does not support the full ui flow as the
Android sdk, yet.

**Comment by ezet** [comment]
What you want is to use `StripeApi.createPaymentMethod()` first, and then pass the resulting ID to `Stripe.confirmPayment()`.

**Comment by ezet** [comment]
`stripeAccount` is not in use, and will be removed.

**Comment by krolaw** [comment]
I did notice that stripeAccount was not being used in the api function calls. Alas without being able to specify the StripeAccount, this library will not be useful for platforms that act on behalf of other stripe accounts...unless I am missing something.

**Comment by ezet** [comment]
I will look into connected accounts soon, as I need it in my own projects.
However, is connected accounts relevant for front end libraries? I don't
think so, that is a matter for the admin libraries, which is another thing
entirely

**Comment by ezet** [comment]
After a quick investigation, connected accounts are not relevant for this library. Your backend service should handle anything related to connected accounts. This library is a flutter implementation of https://github.com/stripe/stripe-android
For your backend, you need to use the backend/admin libraries, which are available for many languages. If you think I'm incorrect, please let me know and link relevant documentation :)

**Comment by krolaw** [comment]
Unfortunately, Stripe docs are particularly weak in this area. I had to contact Stripe support and they took a couple of days to figure it out. (I can forward you the support messages if you're really interested.) I have implemented card payments using using a webviewer, so I'll refer to the logic there - alas, I haven't programmed Java in decades, but would still prefer a more flutter native experience.

Anyway, creating the payment intent as you state should be done serverside with the accountID. However, to handle the payment on the client side you also need the accountID, as the paymentIntent exists only with the vendor's account and without using the accountID, stripe will just complain that it couldn't find the paymentIntent. (This is likely the same for cards/cardpayments as they would be created on the other account, but I was explicitly accessing paymentIntents.) This is what essentially caused much confusion for support as they couldn't see anything wrong with my original web code.

Finally, my working webcode looks something like:
```javascript
var stripe = Stripe("{{.StripePublishableKey}}", {
  stripeAccount: '{{.AccountID}}'
});
...
submitButton.addEventListener('click', function(ev) {
  stripe.handleCardPayment({{.ClientSecret}}, cardElement, {
    payment_method_data: {billing_details: {name: cardholderName.value}}
  }).then(function(result) {
  ...
  });
});
```
As for web docs, quoting Stripe support:
> Then on the front-end, you want to initiate Stripe.js in your vendor's name to have cardHandlePayment process that for them. You'll authenticate as the connected account on the front end in a way similar to how you did for the API call. Here's a sample of how that should look:
>> var stripe = Stripe('pk_test_TYooMQauvdEDq54NiTphI7jx', { stripeAccount: '{{CONNECTED_STRIPE_ACCOUNT_ID}}' }); 
>
> We've got one example of this in action in our documentation, on the page about setting Checkout up for Connect. Here's a link to that if you're curious:
> https://stripe.com/docs/payments/checkout/connect#client-side-code-3

Thus, their one example is refering to subscriptions and not paymentIntent, but their solution did fix the problem. So, if the webdocs are anything to go by, the Java docs for platform operations, might be a little lacking.

Hope that helps (me)!

**Comment by ezet** [comment]
Got it, thank you for the detailed explanation! I'll implement this as soon
as possible. :)

**Comment by ezet** [comment]
I have released 2.2.0, which adds support for this. However, this adds the stripe account header to _all_ requests from that object, and I've not been able to test whether this causes any issues with certain endpoints. Please provide feedback if you discover any issues caused by this. A simple temporary workaround if any such issues arise is to use one object with stripeAccount, and one without it.

**Comment by krolaw** [comment]
Here's an issue:
```dart
Stripe.init(pubKey,stripeAccount: clientID);
print(await Stripe.instance.authenticatePayment(clientSecret));
```
```
Exception has occurred.
_Exception (Exception: Attempted to get singleton instance of Stripe without initialization)
```

Not sure what I'm doing wrong here. I'm not sure it's a good idea to enforce/use singleton's at all for this case. Wouldn't something like:
```dart
final stripe1 = Stripe.init(pubKey,stripeAccount: clientID);
print(await stripe1.authenticatePayment(clientSecret));
```
allow far more flexibility and be less error prone?

**Comment by krolaw** [comment]
The workaround was:
```dart
StripeApi.init(pubKey, stripeAccount: clientID);
Stripe.init(pubKey,stripeAccount: clientID);     
print(await Stripe.instance.authenticatePayment(clientSecret));
```
Which seems like something is broken.

**Comment by ezet** [comment]
Hey! Sorry you had issues with the API, I'll clean it up and fix the above.

You are correct regarding card details, this was meant as a fairly simple, low-level library.
But I'm actually in the process of finishing a small UI form to collect card details right now. It's fairly basic, but should be up next week. 

Please let me know if you have any other issues or requests :)

**Comment by ezet** [comment]
New version with a fix for your issue, and a basic card details form is up :)

**Comment by krolaw** [comment]
Hi @ezet, thanks. I haven't had a chance to look yet. I now see the benefits of having one's own custom interface, although I made use of your cardnumber decorator. I would perhaps suggest having the widgets in a separate package and leave the API lib as just an API lib, then link to the widget lib in examples. I'll have a play prior to the next app update. Thanks.

**Comment by ezet** [comment]
2.4.0 has split the library into two separate sub libraries as you suggested :)
