### ISSUE TITLE
Handling user cancellation with confirmSetupIntentWithPaymentMethod?

### ISSUE THREAD

**Issue by duzenko** [ezet/stripe_sdk#5]
This is the small issue I mentioned in the other ticket.

Basically the question is: how do we handle user aborting on the 3DS confirmation screen? I understand it's not something easily achievable using Intents on Android (don't know about iOS).

Still I would appreciate your suggestions. Suppose the the Stripe confirmation shows up in the web browser, and user instead of 'normal' procedure chooses to navigate back? My app is stuck with a modal activity indicator at that point.

AFAIK the native Stripe SDK shows the action webpage in its own WebView, where it can control navigation events and certainly does not have to worry about process switching. We seem to currently lack a 'native flutter' WebView implementation. Does it make sense to look for 3rd party flutter packages that aim to implement it?

**Comment by ezet** [comment]
This is an issue, yes. The way I have handled it in my app is to simply display a modal dialog as soon as the user is sent to the browser app.
This modal dialog has options to cancel or retry the authentication/confirmation. If they finish or cancel the flow using the web controls, I close the dialog as they are returned to the app. If they closer the browser, or navigate back manually, they will instead be presented with this modal, having the options to either explicitly cancel the attempt, or to relaunch the browser window.

I tried using a web view, but it's rather limited on flutter and didn't work very well. There might be better integrated stripe libraries for flutter at some point, but until then this approach seems to be very versatile, and able to handle any forms of authentication. The trade-offs are worth it for now imo. :) If you have suggestions, I'd be happy to hear them

**Comment by duzenko** [comment]
I would imagine a 'native flutter' WebView should be a solution, as long as it properly supports navigation events for the client. The question is, does such a flutter widget exist at all?

**Comment by ezet** [comment]
No, not native, but it supports navigation events. However, web views do
not support deep links, do you can't detect when the user competes an
action in the view.

**Comment by ezet** [comment]
That said, using a modal screen as described above provides a good solution to the problem. The modal can display some relevant text, e.g. "Payment in progress, please complete the payment to continue", with buttons to cancel and retry/reopen browser. This also prevents unnecessarily cancelling the payment intent if the user switches back to the app by accident, as they need to press "cancel" to confirm the cancellation.
