### ISSUE TITLE
CardForm has a submit button? 

### ISSUE THREAD

**Issue by isrishu** [ezet/stripe_sdk#6]
Hi,
nice library. have been trying to use it but not being a flutter expert, got stuck.
where do I call below code?
onPressed: () async {
                if (formKey.currentState.validate()) {
                  formKey.currentState.save();
                }
}
and I am guessing your Card object gets prefilled when the form is submitted and then I can use that card to create a paymentMethod from card etc
if this is a trivial question, please accept my apologies

**Comment by isrishu** [comment]
when I tried to use the cardForm and a button to handle its validation in a column I am getting a layout error from flutter

**Comment by ezet** [comment]
You can put the button anywhere you like, in the toolbar or below the form. You can use the `key` to access the state of the form from anywhere.

I am afraid I cannot help you with the layout error. 

You are correct in that calling `key.currentState().save()` will populate the provided `Card`, and you can use `toPaymentMethod()`  to create the API data for a payment method.

**Comment by isrishu** [comment]
i am not asking for layout help. I tried to put it in after you CardForm but the ListView that you have used in the cardform does not have the "shrinkWrap: true" property. So flutter throws a layout error like "infinite height" when i use another listview or column in my scaffold to put your form and then a button below it.

**Comment by ezet** [comment]
Oh, I will test and fix that later. I have used a toolbar button in my own project, perhaps try that as a workaround ?

**Comment by isrishu** [comment]
ok, thanks. i guess I will use a toolbar button or FAB then. thanks again man

**Comment by ezet** [comment]
2.4.0 replaces the ListView in the form with a Column, so you can add the button now. There is a minor breaking change, please see the changelog.
